### ISSUE TITLE
网站是不是还没完全搭好？

### ISSUE THREAD

**Issue by wangwill** [keyacid/keybeaker#3]
![image](https://cloud.githubusercontent.com/assets/9379983/26716857/50c2831a-47ba-11e7-8786-c55f484f8de5.png)

如图 一直显示 invalid signature

**Comment by yvbbrjdr** [comment]
你好 你需要使用Sign来计算Signature
就像你登录的时候那样

**Comment by wangwill** [comment]
计算哪一个Sign 的Sig
尝试了 Sender Public Key、Sender Public Key、Content 都不行啊

而且每次是新的Sig 不影响？
